// AUTO-GENERATED by scripts/generate-offline-dictionary.mjs
// Build/dev replaces this stub with the bundled 5000-word English-Vietnamese dataset.
export const OFFLINE_DICTIONARY_5000_COUNT = 0;
export const OFFLINE_DICTIONARY_5000: Record<string, Array<{p:string;i?:string;v:string[];e:string[];f:string[]}>> = {};
export const OFFLINE_DICTIONARY_ALIASES: Record<string, string> = {};
