// AUTO-GENERATED by scripts/generate-offline-dictionary.mjs
// Build/dev replaces this stub with the bundled 10,000-word English-Vietnamese dataset.
export const OFFLINE_DICTIONARY_10000_COUNT = 0;
export const OFFLINE_DICTIONARY_10000: Record<string, Array<{p:string;i?:string;v:string[];e:string[];f:string[];x?:Array<[string,string]>}>> = {};
export const OFFLINE_DICTIONARY_10000_ALIASES: Record<string, string> = {};
