// AUTO-GENERATED by scripts/generate-offline-dictionary.mjs
// Build/dev replaces this stub with the complete validated English-Vietnamese lexicon.
// The legacy filename is kept to avoid unnecessary import churn.
export const OFFLINE_DICTIONARY_SCHEMA_VERSION = 0;
export const OFFLINE_DICTIONARY_10000_COUNT = 0;
export const OFFLINE_DICTIONARY_EXAMPLE_WORD_COUNT = 0;
export const OFFLINE_DICTIONARY_EXAMPLE_SENTENCE_COUNT = 0;
export const OFFLINE_DICTIONARY_10000: Record<string, Array<{p:string;i?:string;v:string[];e:string[];f:string[];x?:Array<[string,string]>}>> = {};
export const OFFLINE_DICTIONARY_10000_ALIASES: Record<string, string> = {};
