// AUTO-GENERATED by scripts/generate-offline-dictionary.mjs
// Primary dictionary source: thichhoc-org/thichhoc-dict (CC BY-SA 4.0).
// Supplemental source: Vietnamese Wiktionary via Wiktextract/Kaikki.
// Bilingual example source: Tatoeba via ManyThings (CC BY 2.0 FR).
// LexiGlass bundles the full validated source set instead of a frequency-limited subset.
// Do not edit manually.
export const OFFLINE_DICTIONARY_SCHEMA_VERSION = 4;
export const OFFLINE_DICTIONARY_10000_COUNT = 214590;
export const OFFLINE_DICTIONARY_ALIAS_COUNT = 146613;
export const OFFLINE_DICTIONARY_EXAMPLE_WORD_COUNT = 11979;
export const OFFLINE_DICTIONARY_EXAMPLE_SENTENCE_COUNT = 22291;
export const OFFLINE_DICTIONARY_SHARD_KEYS = ["0","1","2","3","4","5","6","7","8","9","_","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"] as const;
